### ISSUE TITLE
order convention for j_ij matrix

### ISSUE THREAD

**Issue by alihaydaroglu** [eltrompetero/coniii#11]
what is the ordering convention for the j_ij coupling matrix? it seems like it is a `n * (n-1) / 2` sized matrix, but how is it ordered? I have a full, `n*n` j_ij matrix (symmetric, with 0 diagonals) that I want to convert to your convention, but I'm not exactly sure how to.

@eltrompetero Thanks for the great software package! I'm looking forward to using it.

**Comment by eltrompetero** [comment]
It’s the upper triangle of the matrix read in by row. You can access this by using Jij[numpy.triu_indices(n, k=1)], assuming your matrix is Jij.

**Comment by eltrompetero** [comment]
You can also use scipy.spatial.distance.squareform to switch between these two representations.

**Comment by alihaydaroglu** [comment]
Thank you so much!
