### ISSUE TITLE
easy Ising sampling

### ISSUE THREAD

**Issue by bcdaniels** [eltrompetero/coniii#14]
I wanted to do some very basic sampling from a pairwise Ising model—I guess I assumed this would be a one-liner in `coniii`, but not so (or not yet!).

I think this could be useful to include even if it's not used at a low level (since we will probably want to remain open to more general maximum entropy models).

Here's one implementation.  Is this the best way to do it?

```
def sample_ising(Jflat,n_samples,n_cpus=1,seed=0):
    """
    Jflat            : N individual parameters followed by 
                       N(N-1)/2 pairwise parameters (ordered
                       as in np.triu_indices(N,k=1))
    """
    # set up coniii metropolis sampler
    calc_e_fast, calc_observables, _ = coniii.utils.define_ising_helper_functions()
    rng = np.random.RandomState(seed=seed)
    multipliers = Jflat
    n = 0.5 * (-1 + np.sqrt(1 + 8*len(multipliers)) )
    assert n == int(n),"The length of Jflat does not correspond to an integer number of spins"
    calc_e = lambda s, multipliers : -calc_observables(s).dot(multipliers)
    sampler = coniii.samplers.Metropolis( int(n), multipliers, calc_e,
                                          n_cpus=n_cpus, rng=rng )
    
    # generate samples
    if n_cpus > 1:
        sampler.generate_samples_parallel(n_samples)
    else:
        sampler.generate_samples(n_samples)
    return sampler.samples
```

Notes:
- I didn't use `calc_e_fast` due to typing issues, but maybe I just need to put things into numpy arrays?
- We may want to catch non-integer `n` within the `Solver` class more generally.
- Running this in the simplest case—e.g. `sample_ising([0,0,0],100)`—gives poor results because when the energy is always zero every spin is always flipped, meaning you always flip between only the initial state and its inverse.  This is of course a problem with the metropolis algorithm generally, but we might avoid this by e.g. starting from multiple starting points by default (I haven't yet thought this through carefully).  Running with larger `n_cpus` already effectively does this.

**Comment by eltrompetero** [comment]
Response to your notes:
- You might use a try/except statement. And yes, float numpy arrays are necessary because it's a typed function.
- That's easy enough. I'll tag for later.
- I believe there's an option for not flipping spins sequentially.

**Comment by eltrompetero** [comment]
How about the latest commit? See bottom of https://github.com/eltrompetero/coniii/blob/py3/coniii/samplers.py

**Comment by bcdaniels** [comment]
Yes, I think that should work.

I looked more into my last issue, which was more subtle than I thought.  I think whenever `n_iters` is divisible by 2, we can get into trouble in the case when all states are equally likely (e.g. when all energies are exactly zero).  This is because we can never get to a state with the opposite parity of the initial state.

**Comment by bcdaniels** [comment]
Also, I don't know the convention, but for the extra arguments passed to the sampler, I would usually include these like so:
```
def sample_ising(Jflat, n_samples,
                 n_cpus=None,
                 seed=None,
                 **generate_samples_kw):
```
so that you can call `sample_ising([0,0,0],100,n_iters=999)` instead of `sample_ising([0,0,0],100,generate_samples_kw={'n_iters':999})`?

**Comment by eltrompetero** [comment]
I think there's a choice here because I could imagine in a future version that we have to pass keyword args into the declaration of the sampler as well, i.e., if we used Wolff instead of Metropolis.

Is it intuitive and clear that regular extra keyword args go into generate_samples whereas other kwargs are more specific and are more "optional"?

**Comment by bcdaniels** [comment]
Hm, not sure.  I guess as a user I don't really want to have to think about which arguments get passed to which internal function.  In the future, couldn't we automatically parse out which arguments go to which function (e.g. using the name of each argument)?

Also, on another note: the current version ends up being very slow when run multiple times because `define_ising_helper_functions` keeps recompiling C code (I think).  I fixed this in my code by calling `define_ising_helper_functions` once outside of `sample_ising`.  Maybe it makes sense to have a separate `ising` submodule that compiles these things when it's imported?

**Comment by eltrompetero** [comment]
`define_ising_helper_functions` is not that slow.

```$
In [9]: %timeit define_ising_helper_functions()                     
465 ms ± 59.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) 
```

One reason for slowdown is that you're not setting `n_cpus=1`. This means that the multiprocess module has to instantiate threads on each run, which is slow. There's not a way around this without keeping a Pool instance outside the function and modifying the Metropolis class to handle manual setting of the pool.

**Comment by bcdaniels** [comment]
I'm not sure without doing more fiddling.  At the moment, I just know that if I run `define_ising_helper_functions` outside of `sample_ising`, I get this:
```
In [7]: %timeit samples = sample_ising([0.,0.,0.],100)                       
460 ms ± 6.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
whereas if I include it within `sample_ising`, I get this:
```
In [11]: %timeit samples = sample_ising([0.,0.,0.],100)                      
1.9 s ± 17.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Somehow the difference is more than the 0.5 s takes to run `define_ising_helper_functions` by itself.  I'm not sure if this is because of the multiprocess stuff you mentioned?  For now I'm just going to use my own faster function, but it seems like something worth addressing in coniii eventually.

**Comment by eltrompetero** [comment]
I've implemented a completely different approach that should help with this issue. I've extended the Python module using the Boost C++ module. I'm looking at something like 100x speedup for Metropolis sampling. Currently, the bleeding edge version only works for Linux because compiling C++ using distutils is tricky.
