### ISSUE TITLE
Streamline typical use cases

### ISSUE THREAD

**Issue by bcdaniels** [eltrompetero/coniii#17]
A typical use case currently takes more steps than maybe it should.  E.g. to solve an inverse ising problem using MPF:
```
_,calc_observables,_ = coniii.define_ising_helpers_functions()
solver = coniii.MPF(len(samples[0]),calc_observables=calc_observables,adj=coniii.adj)
estMultipliers = solver.solve(samples)
```
Ideally, I would think we could do something like
```
solver = coniii.MPF(samples)
estMultipliers = solver.solve()
```
where MPF would default to inverse ising.

Also, we may want to return the multipliers in a friendlier form by default (e.g. a matrix instead of a list).

**Comment by eltrompetero** [comment]
See new version 2.0 that I just uploaded tonight for streamlined interface for Ising problems.

I am against changing the way multipliers are handled because generalization to higher order correlations is unwieldy in matrix format. It's straightforward to transform to matrix using `scipy.spatial.distance.squareform` which is loaded by default in the utils.py module.

**Comment by bcdaniels** [comment]
This looks nice!

I had some trouble finding the new jupyter usage guide because the readme currently points to the version on the master branch, which is now outdated.  (Maybe it's time to merge the py3 branch into master?)

**Comment by bcdaniels** [comment]
I still do think it would be nice to have a more obvious way to get the parameters in matrix form.  (Even I got confused about how to do this recently.)  Maybe we mention `squareform` directly in the docstring?

**Comment by eltrompetero** [comment]
Yikes. I've fixed those links for the moment.

I've created a couple new helper functions vec2mat and mat2vec as shown in the test case here:
```python
def test_vec2mat():
    for n in range(3,100):
        x = np.random.rand(n+n*(n-1)//2)
        assert np.array_equal(x, mat2vec(vec2mat(x)))
        xvec, xmat = vec2mat(x, True)
        assert np.array_equal(xvec,x[:n])
```
