### ISSUE TITLE
Incorporate Emcee MCMC sampler?

### ISSUE THREAD

**Issue by bcdaniels** [eltrompetero/coniii#19]
I ran across Emcee, which implements MCMC sampling in Python:

https://emcee.readthedocs.io/en/stable/

This could be useful for coniii as another well-tested sampler to compare with.  (I haven't looked too deeply to understand its performance or efficiency.)

**Comment by eltrompetero** [comment]
For more specific use...I've implemented our sampler using Boost for a ~1000x speedup. You're welcome to try to get it to compile on your system. Boost makes distribution somewhat difficult---mostly because of my unfamiliarity with it.

**Comment by eltrompetero** [comment]
I've added the Boost sampler to the latest commit. One has to first install the Boost library. Do you want to try it out?
