### ISSUE TITLE
Maximum system size? 

### ISSUE THREAD

**Issue by saynbabul** [eltrompetero/coniii#29]
For the MCH method, I am wondering if there is a maximum system size? n=35 system size with the same MCH parameters, the results returned make sense, and then precisely at the n >= 36 barrier, the returned couplings have extremely different behaviour. This occurs for any randomly selected n = 36 (or greater) subset of my data.

**Comment by eltrompetero** [comment]
I've used it to solve N>=100.

You may need to tweak the learning weights. MCH is quite finicky once you surpass the linear assumptions.

Let me know if that's not the solution.

**Comment by saynbabul** [comment]
I did try that, but I still seem to be getting an issue that stems from: 

"RuntimeWarning: divide by zero encountered in double_scalars
  ZFraction = len(dE) / np.exp(logsumexp(-dE))” 

after the first one or two iterations. I was wondering if you’ve seen that before? It is strange given that the denominator should never be zero.

**Comment by eltrompetero** [comment]
You might have large values in your energy change function.

There is an option to output the results of iterations of the MCH sampler. You can check if your chosen step size is converging.

There is also the pseudolikelihood method.

**Comment by eltrompetero** [comment]
Any luck with checking the output?

**Comment by saynbabul** [comment]
I did print the error flags, which do seem to continue to decrease, even after the error. 

I’ve been playing around with the parameters and I found that after a certain maximum sample size (n~35) , the error always occurs immediately after the second iteration, no matter what set of (n > 35) sample I choose. 

the only way to change this seems to be by scaling down the initial eta value from 1. Ie. at (max eta = 0.5 at counter = 0) I can get the maximum size of the system up to 60, and then scaling it down even further gets me to an even higher limit. 

I’m not sure if if this makes sense as a fix?

**Comment by eltrompetero** [comment]
Great. Yes, the MCH algorithm is finicky. 

Eta controls the overall scaling of the gradient descent step. When you have a larger system, then you have a larger gradient vector, and the norm will increase.

To quote from the paper, https://openresearchsoftware.metajnl.com/articles/10.5334/jors.217/


> In practice, MCH can be difficult to tune properly and one must check in on the progress of the algorithm often. One issue is choosing how to set the learning rule parameters η and ∈. One suggestion for η is to shrink it as the inverse of the number of iterations [17]. Another issue is that parameters cannot be changed by too much when using the MCH approximation step or the extrapolation to λk′ will be inaccurate and the algorithm will fail to converge. In ConIII, this can be controlled by setting a bound on the maximum possible change in each parameter Δλmax and restricting the norm of the vector of change in parameters k 2k .

I will close this issue now.
