### ISSUE TITLE
User manual not up to date

### ISSUE THREAD

**Issue by cvanelteren** [eltrompetero/coniii#31]
The user manual is filled with code that does not run as advertised.

**Comment by eltrompetero** [comment]
Would you be kind enough to provide some details?

Some of the issues you were running into may have been resolved in the newest update v3.0.1. I am able to run the notebook on a clean installation following the updated instruction in the readme.

**Comment by eltrompetero** [comment]
I will close this issue. Let me know if you do try the new version.
