### ISSUE TITLE
GLIBC_2_29 not found when importing coniii

### ISSUE THREAD

**Issue by rmldj** [eltrompetero/coniii#36]
I installed `coniii` using a conda environment without any errors. Unfortunately when importing the package I got the following error
```
  File "/home/romuald/miniconda3/envs/ising/lib/python3.10/site-packages/coniii/samplers.py", line 40, in <module>
    from .samplers_ext import BoostIsing, BoostPotts3
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/romuald/miniconda3/envs/ising/lib/python3.10/site-packages/coniii/samplers_ext.cpython-310-x86_64-linux-gnu.so)
```
On our computational server unfortunately we have an older version:
```
ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
```
Is it possible to install a version compatible with this library (or is there a workaround?)?
I would be grateful for your help!

**Comment by eltrompetero** [comment]
Hello! I’m not sure, but is this possibly an error with your PATH env variable? If it compiles the Boost extension fine, then presumably it can run it. If you’re running it on a cluster, do you know if the same libraries are mirrored on every server?Sent from my iPhone- - -- --- ----- --------Edward D Lee | PhDAustrian Science Fund ESPRIT Fellow | CSH ViennaJosefstaedter Strasse 39 | 1080 Vienna, Austriahttps://eddielee.co On 16.11.2023, at 17:51, rmldj ***@***.***> wrote:﻿
I installed coniii using a conda environment without any errors. Unfortunately when importing the package I got the following error
  File "/home/romuald/miniconda3/envs/ising/lib/python3.10/site-packages/coniii/samplers.py", line 40, in <module>
    from .samplers_ext import BoostIsing, BoostPotts3
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/romuald/miniconda3/envs/ising/lib/python3.10/site-packages/coniii/samplers_ext.cpython-310-x86_64-linux-gnu.so)

On our computational server unfortunately we have an older version:
ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27

Is it possible to install a version compatible with this library (or is there a workaround?)?
I would be grateful for your help!

**Comment by rmldj** [comment]
I had a similar problem on my laptop (alas with an old Linux Mint 18.3). I am not sure if boost is compiled when being installed - the installation somehow is too quick...

I also tried searching for alternate versions of `libm.so`, but I see only the system versions - no local (potentially newer?) version in the Anaconda directories..

For the moment I erased the file `coniii/samplers_ext.cpython-310-x86_64-linux-gnu.so` and then it seems that I fallback to the slower samplers.

**Comment by eltrompetero** [comment]
Just to double check, you tried the manual installation instructions in the README?

Somewhere through the installation process (maybe you have to scroll up) it should print out whether or not the boost extension compiled correctly.

**Comment by rmldj** [comment]
No - I tried the conda version and pip - it ran without any problems...

**Comment by eltrompetero** [comment]
I would give the manual install a try. Should be quite quick. May resolve your issues.

**Comment by rmldj** [comment]
Thanks! I think it worked...
