### ISSUE TITLE
No define_ising_helpers_functions & pseudolikelihood scaling

### ISSUE THREAD

**Issue by rxu2** [eltrompetero/coniii#7]
`pip3 install coniii`

followed : https://github.com/eltrompetero/coniii/blob/master/ipynb/usage_guide.ipynb

```python3
>>> from coniii import *
>>> define_ising_helpers_functions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'define_ising_helpers_functions' is not defined

```

Unit test also used that function: https://github.com/eltrompetero/coniii/blob/py3/coniii/test_solvers.py

What is the correct way to use the pseudo likelihood to fit Ising model?

**Comment by rxu2** [comment]
Should be `define_ising_helper_functions` instead of `define_ising_helpers_functions` according to the unit test.

**Comment by rxu2** [comment]
Can coniii handle 2k atoms if I use pseudo likelihood? How long will that take? How about 200k? 

I can't run the unit test when i modify the number of atoms to 100 because that is too big for the enumeration method.

**Comment by eltrompetero** [comment]
Sorry about the delay in getting back to you...I don't seem to get notifications when new issues are opened...hm.

Thanks for pointing out that bug.

You certainly do not want to use Enumerate for anything beyond 15 spins unless you have a lot of memory and time to wait around. Obviously it will depend on your system, but computational cost scales exponentially with N (https://github.com/eltrompetero/coniii/blob/py3/guide/guide.pdf) so don't expect to get much further.

Pseudolikelihood is pretty fast and low memory, but even that scales polynomially as N^3 for the Hessian calculation and N^2 for memory for storing the coupling matrix (I think). So it may be pushing the limits if you are considering 2,000 spins. You might want to keep tabs on memory and speed.

As for another order magnitude, if you had a very sparse matrix...this is would be possible for a desktop computer, but such a routine is not currently supported. I could imagine implementing a sparse version of pseudo likelihood would be relatively straightforward. I'd be curious to hear more if you follow up on that.

**Comment by eltrompetero** [comment]
@rxu2 I'm going to go ahead and close this issue since I haven't heard back from you.
